CREATE PACKAGE EXAMPLE AS
BEGIN
	FUNCTION EXTRACT_BIT (
		p_number BIGINT,
		p_index BIGINT
	) 
	RETURNS BIGINT;
END


CREATE PACKAGE BODY EXAMPLE AS
BEGIN
	FUNCTION EXTRACT_BIT (
		p_number BIGINT,
		p_index BIGINT
	) 
	RETURNS BIGINT
  	EXTERNAL NAME 'ru.example.Math.extractBit(long, short)'
  	ENGINE JAVA;
END
