CREATE TABLE RDB$DBMS_RANDOM (
    SESSION_ID BIGINT NOT NULL,
    SEED BIGINT NOT NULL,
    CONSTRAINT PK_SESSION_ID PRIMARY KEY (SESSION_ID));



















SET TERM ^ ;
CREATE OR ALTER PACKAGE  DBMS_RANDOM
AS
BEGIN
	PROCEDURE INITIALIZE(p_seed INT);

	
	PROCEDURE TERMINATE();

	
	PROCEDURE SEED(p_seed VARCHAR);

	
	FUNCTION RANDOM ()  RETURNS INT;


	FUNCTION NORMAL() RETURNS  DECFLOAT;

	
	FUNCTION RAND_STRING (
		p_otp CHAR,
		p_len INT
	) RETURNS VARCHAR;

		
	FUNCTION RAND_VALUE (
		p_low DECFLOAT DEFAULT -1,
		p_high DECFLOAT DEFAULT 1
	)  RETURNS  DECFLOAT;



----------------------------------------
----СИСТЕМНЫЕ ФУНКЦИИ----
----------------------------------------



	FUNCTION GET_SESSION_ID () RETURNS INT;

	
	FUNCTION GET_SEED (P_ROUND INT DEFAULT 1) RETURNS INT;

	
	PROCEDURE SET_SEED(
		P_SEED INT,
		P_ROUND INT DEFAULT 1
	);

	
	FUNCTION JAVA_NEW_SEED(
		P_SEED INT,
		P_ROUND INT DEFAULT 1
	) RETURNS INT;

		
	FUNCTION JAVA_SEED(P_SEED VARCHAR) RETURNS INT;

	
	FUNCTION JAVA_VALUE(
		p_seed INT,
		p_low DECFLOAT  DEFAULT -1,
		p_high DECFLOAT  DEFAULT 1
	) RETURNS DECFLOAT;


	FUNCTION JAVA_STRING(
		p_seed INT,
		p_otp CHAR,
		p_len INT
  	) RETURNS VARCHAR;


  	FUNCTION JAVA_NORMAL(
		p_seed INT
  	) RETURNS DECFLOAT;
END^
RECREATE PACKAGE BODY DBMS_RANDOM
AS
BEGIN
	PROCEDURE INITIALIZE(p_seed INT) AS
	BEGIN
		CALL SET_SEED(p_seed);
	END

	
	PROCEDURE TERMINATE() AS BEGIN END

	
	PROCEDURE SEED(p_seed VARCHAR) AS
	BEGIN
		CALL SET_SEED(JAVA_SEED(p_seed));
	END

	
	FUNCTION RANDOM () RETURNS INT AS
	BEGIN
		RETURN GET_SEED();
	END

	  	
	FUNCTION NORMAL() RETURNS  DECFLOAT AS
	BEGIN
		RETURN JAVA_NORMAL(GET_SEED());
	END

	  	
	FUNCTION RAND_STRING (
		p_otp CHAR,
		p_len INT
	) RETURNS VARCHAR AS
		DECLARE V_SEED INT;
	BEGIN
		IF (p_len <= 0) THEN
			RETURN null;
		V_SEED = GET_SEED(p_len);
		RETURN JAVA_STRING(V_SEED, p_otp, p_len);
	END


	FUNCTION RAND_VALUE (
		p_low DECFLOAT,
		p_high DECFLOAT
	)  RETURNS  DECFLOAT AS
	BEGIN
		RETURN JAVA_VALUE(GET_SEED(), p_low, p_high);
	END



----------------------------------------
----СИСТЕМНЫЕ ФУНКЦИИ----
----------------------------------------



	FUNCTION GET_SESSION_ID() RETURNS INT AS
  	BEGIN
		RETURN (SELECT RDB$GET_CONTEXT('SYSTEM', 'SESSION_ID') FROM RDB$DATABASE);
  	END

  	
  	FUNCTION GET_SEED(P_ROUND INT) RETURNS  INT AS
		DECLARE V_SESSION_ID INT = GET_SESSION_ID();
		DECLARE V_SEED INT;
  	BEGIN
		SELECT SEED FROM RDB$DBMS_RANDOM WHERE SESSION_ID = :V_SESSION_ID INTO :V_SEED;
  		V_SEED = COALESCE(V_SEED, V_SESSION_ID);
		CALL SET_SEED(V_SEED, P_ROUND);
		RETURN V_SEED;
  	END


  	PROCEDURE SET_SEED(
  		P_SEED INT,
		P_ROUND INT
	) AS
		DECLARE V_SESSION_ID INT = GET_SESSION_ID();
  	BEGIN
  		P_SEED = JAVA_NEW_SEED(P_SEED, P_ROUND);
		UPDATE RDB$DBMS_RANDOM SET SEED = :P_SEED WHERE SESSION_ID = :V_SESSION_ID;
		IF (ROW_COUNT = 0) THEN
			INSERT INTO RDB$DBMS_RANDOM (SESSION_ID, SEED) VALUES (:V_SESSION_ID, :P_SEED);
  	END

  	
	FUNCTION JAVA_NEW_SEED(
		P_SEED INT,
		P_ROUND INT
	) RETURNS INT
	EXTERNAL NAME 'ru.example.Random2.round(int, int)'
	ENGINE JAVA;

  	
	FUNCTION JAVA_SEED(P_SEED VARCHAR) RETURNS INT
	EXTERNAL NAME 'ru.example.Random2.seed(String)'
	ENGINE JAVA;

  		
	FUNCTION JAVA_VALUE(
		p_seed INT,
		p_low DECFLOAT,
		p_high DECFLOAT
	) RETURNS DECFLOAT
	EXTERNAL NAME 'ru.example.Random2.value(int, BigDecimal, BigDecimal)'
  	ENGINE JAVA;


  	FUNCTION JAVA_STRING(
		p_seed INT,
		p_otp CHAR,
		p_len INT
  	) RETURNS VARCHAR
	EXTERNAL NAME 'ru.example.Random2.string(int, String, int)'
  	ENGINE JAVA;


  	FUNCTION JAVA_NORMAL(
		p_seed INT
  	) RETURNS DECFLOAT
	EXTERNAL NAME 'ru.example.Random2.normal(int)'
  	ENGINE JAVA;
END^
SET TERM ; ^
